palette = "terminal_theme"
command_timeout = 1000
add_newline = false
# format = """$directory$shell$all$fill􁟬  ${custom.airpods} $line_break$character"""
format = """$directory$shell$all$fill$line_break$character"""

[character]
# success_symbol = "[􀄵 ](teal)"
# success_symbol = "[􀄫 ](bold teal)"
success_symbol = "[➜](bold teal)"
error_symbol = "[➜](red)"
vimcmd_symbol = "[󰕷 ](bold rosewater)"

[fill]
symbol = ' '

[shell]
fish_indicator = "🌊"
unknown_indicator = "👀"
nu_indicator = "🌿"
disabled = false

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
truncation_symbol = "…/"
truncation_length = 4
read_only = " 󰌾"

# [custom.airpods]
# command = "echo 􀪷  "
# when = "blueutil --connected | grep -q 'name: \".*AirPods'"
# shell = ["fish", "-c"]
# format = "$output"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = "(bold maroon) "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[palettes.terminal_theme]
rosewater = "#b48ead"
flamingo = "#b48ead"
pink = "#b48ead"
mauve = "#b48ead"
red = "#bf616a"
maroon = "#bf616a"
peach = "#ebcb8b"
yellow = "#ebcb8b"
green = "#a3be8c"
teal = "#88c0d0"
sky = "#81a1c1"
sapphire = "#8fbcbb"
blue = "#81a1c1"
lavender = "#81a1c1"
text = "#d8dee9"
subtext1 = "#596377"
subtext0 = "#596377"
overlay2 = "#596377"
overlay1 = "#e5e9f0"
overlay0 = "#e5e9f0"
surface2 = "#e5e9f0"
surface1 = "#e5e9f0"
surface0 = "#e5e9f0"
base = "#2e3440"
mantle = "#2e3440"
crust = "#2e3440"
