# DeepSeek API key (for Pi DeepSeek provider) - set your own, do not commit it
set -gx DEEPSEEK_API_KEY "your-api-key-here"


# Added by Antigravity CLI installer
set -gx PATH "/Users/hakanuzum/.local/bin" $PATH

# --- From Huguesmmm/dotfiles, adapted ---
if status is-interactive
    starship init fish | source
    zoxide init fish | source
    source /opt/homebrew/opt/fzf/shell/key-bindings.fish
end

set -gx EDITOR nvim

# BEGIN fish_color (auto-generated by set-terminal-theme.py)
set fish_color_command 81a1c1
set fish_color_normal d8dee9
set fish_color_autosuggestion 596377
set fish_color_param d8dee9
set fish_color_option ebcb8b
set fish_color_quote a3be8c
set fish_color_redirection 88c0d0
set fish_color_end b48ead
set fish_color_error bf616a
set fish_color_comment 596377
set fish_color_operator 88c0d0
set fish_color_escape 88c0d0
set fish_color_cwd 81a1c1
# END fish_color (auto-generated)

# lsd's own file-type name colors (di/fi/ln/ex), independent of colors.yaml.
# fi=0 forces regular file names to inherit the terminal foreground
# instead of lsd's built-in near-white default.
set -gx LS_COLORS "di=1;38;2;129;161;193:fi=38;2;216;222;233:ln=1;38;2;136;192;208:ex=1;38;2;163;190;140"

# lsd aliases
alias ls="lsd -F"
alias la="lsd -AF"
alias ll="lsd -lAF"
alias lg="lsd -F --group-dirs=first"
alias tree="lsd -AF --tree"

# fzf styling (auto-generated by set-terminal-theme.py)
set -gx FZF_DEFAULT_OPTS "
  --color=bg+:#596377,bg:-1,spinner:#b48ead,hl:#bf616a \
  --color=fg:#d8dee9,header:#bf616a,info:#b48ead,pointer:#b48ead \
  --color=marker:#81a1c1,fg+:#d8dee9,prompt:#b48ead,hl+:#bf616a \
  --color=selected-bg:#e5e9f0 \
  --color=border:#596377,label:#d8dee9,gutter:-1
  --no-border
  --preview-window noborder
  --margin=1
  --padding=2
  --layout=reverse
"

function fish_greeting
  if string match -q "xterm-kitty" $TERM; or set -q GHOSTTY_RESOURCES_DIR
    kitten icat --clear --z-index 1 --align=left ~/dotfiles/utils/pictures/robot_small.png
  end
end

function clear --wraps fish_clear
  command clear
  if string match -q "xterm-kitty" $TERM; or set -q GHOSTTY_RESOURCES_DIR
    fish_greeting
  end
end
