#!/usr/bin/env bash
set -euo pipefail

# Regenerate AgentGlyphData.swift from simple-icons.
#
# The tab bar marks an agent CLI with that tool's own logo. Drawing those from
# memory produces something that is recognisably wrong, which is worse than no
# mark at all, so they come from simple-icons: single-path, monochrome, one
# 24x24 viewBox, and the icon files are CC0. The marks themselves remain the
# trademarks of their owners and are used here only to identify the program
# running in a tab.
#
# Only tools with an icon in simple-icons appear in the generated table. The rest
# fall back to a letter mark in AgentBadge — deliberately, rather than shipping an
# invented logo. Re-run this when a missing tool gets an upstream icon.
#
# Usage: scripts/fetch-agent-icons.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$PROJECT_ROOT/Notchshell/Sources/Notchshell/Terminal/AgentGlyphData.swift"
BASE="https://cdn.jsdelivr.net/npm/simple-icons@latest/icons"

# AgentKind case  :  simple-icons slug
#
# `codex` takes the OpenAI mark and `grok` the X mark: neither tool has its own
# entry upstream, and both are that vendor's CLI. Anything whose vendor mark would
# be a guess is left out entirely.
MAPPINGS=(
    "claude:claude"
    "codex:openai"
    "gemini:googlegemini"
    "grok:x"
    "copilot:githubcopilot"
    "cursor:cursor"
    "opencode:opencode"
    "qwen:qwen"
    "ollama:ollama"
)

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

{
    echo "// Generated by scripts/fetch-agent-icons.sh — do not edit by hand."
    echo "//"
    echo "// Icon paths from simple-icons (CC0). Each is a single filled path in a 24x24"
    echo "// viewBox, which is why AgentGlyphShape needs nothing but the 'd' string."
    echo "// The marks are the trademarks of their respective owners and appear here only"
    echo "// to identify the program running in a tab."
    echo ""
    echo "enum AgentGlyphData {"
    echo "    /// SVG path data, 24x24 viewBox, non-zero winding."
    echo "    static let paths: [AgentKind: String] = ["
} > "$TMP/out.swift"

for mapping in "${MAPPINGS[@]}"; do
    agent="${mapping%%:*}"
    slug="${mapping##*:}"
    echo "==> $agent <- $slug"
    if ! curl -sf --max-time 30 "$BASE/$slug.svg" -o "$TMP/$slug.svg"; then
        echo "    FAILED to download $slug" >&2
        exit 1
    fi
    count="$(grep -c '<path' "$TMP/$slug.svg" || true)"
    if [ "$count" != "1" ]; then
        echo "    expected exactly one <path> in $slug.svg, found $count" >&2
        exit 1
    fi
    d="$(sed -n 's/.*<path d="\([^"]*\)".*/\1/p' "$TMP/$slug.svg")"
    if [ -z "$d" ]; then
        echo "    could not extract path data from $slug.svg" >&2
        exit 1
    fi
    title="$(sed -n 's/.*<title>\([^<]*\)<\/title>.*/\1/p' "$TMP/$slug.svg")"
    printf '        // %s — simple-icons "%s"\n        .%s: "%s",\n' \
        "$title" "$slug" "$agent" "$d" >> "$TMP/out.swift"
done

{
    echo "    ]"
    echo "}"
} >> "$TMP/out.swift"

mv "$TMP/out.swift" "$OUTPUT"
echo "==> Wrote $OUTPUT"
